# Generated by Django 3.2.8 on 2021-11-03 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0038_auto_20211030_2109'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lti_toolbox', '0002_lticonsumer_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='LTIConsumerProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.SmallIntegerField(choices=[(0, 'UOC_CAMPUS'), (1, 'MOODLE'), (2, 'CANVAS')], default=0)),
                ('user_creation', models.BooleanField(default=False)),
                ('instructor_creation', models.BooleanField(default=False)),
                ('learner_creation', models.BooleanField(default=False)),
                ('course_creation', models.BooleanField(default=False)),
                ('group_creation', models.BooleanField(default=False)),
                ('user_username_field', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('course_code_field', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('group_code_field', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('consumer', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='lti_toolbox.lticonsumer')),
            ],
        ),
        migrations.CreateModel(
            name='LTIProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_username', models.CharField(default=None, max_length=250)),
                ('custom_photo', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('custom_firstname', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('custom_surname', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('custom_fullname', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('custom_username', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('custom_sessionid', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('ext_user_username', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('lis_person_name_given', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('lis_person_name_family', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('lis_person_name_full', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('lis_person_contact_email_primary', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('consumer', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='lti_toolbox.lticonsumer')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('consumer', 'user_username'), ('consumer', 'user')},
            },
        ),
        migrations.CreateModel(
            name='LTIGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(default=None, max_length=250)),
                ('context_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('context_label', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('context_title', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('custom_domain_id', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('custom_domain_code', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('consumer', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='lti_toolbox.lticonsumer')),
                ('group', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.coursegroup')),
            ],
            options={
                'unique_together': {('consumer', 'group'), ('consumer', 'group_code')},
            },
        ),
        migrations.CreateModel(
            name='LTICourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(default=None, max_length=250)),
                ('custom_domain_coditercers', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('custom_domain_year', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('custom_domain_semester', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('custom_domain_pt_template', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('context_id', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('context_title', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('context_label', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('consumer', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='lti_toolbox.lticonsumer')),
                ('course', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.course')),
            ],
            options={
                'unique_together': {('consumer', 'course_code')},
            },
        ),
    ]
