# Generated by Django 3.2.8 on 2021-11-03 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lticonsumerproperties',
            name='consumer',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lti_toolbox.lticonsumer'),
        ),
    ]
