# Generated by Django 3.2.8 on 2021-12-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0003_alter_ltigroup_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lticourse',
            name='custom_domain_pt_template',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
