# Generated by Django 3.2.8 on 2021-12-22 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_auto_20211220_2222'),
        ('lti', '0004_alter_lticourse_custom_domain_pt_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lticourse',
            name='consumer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lti_toolbox.lticonsumer'),
        ),
        migrations.AlterField(
            model_name='ltigroup',
            name='consumer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lti_toolbox.lticonsumer'),
        ),
        migrations.AlterField(
            model_name='ltigroup',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.coursegroup'),
        ),
        migrations.AlterField(
            model_name='ltiprofile',
            name='consumer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lti_toolbox.lticonsumer'),
        ),
    ]
