# Generated by Django 3.2.8 on 2021-10-15 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code_base_result',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_submission', to='web.testsubmission'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code_test_result',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_submission', to='web.testsubmission'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'CREATED'), (1, 'UPLOADING'), (2, 'UPLOADED'), (3, 'CLONING'), (4, 'CLONED'), (5, 'VALIDATING'), (6, 'VALID'), (7, 'TESTING'), (8, 'PROCESSED'), (9, 'INVALID'), (10, 'ERROR'), (11, 'TIMEOUT')], default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'CREATED'), (1, 'UPLOADING'), (2, 'UPLOADED'), (3, 'CHECKING'), (4, 'VALID'), (5, 'TESTING'), (6, 'PROCESSED'), (7, 'INVALID'), (8, 'ERROR'), (9, 'TIMEOUT')], default=0),
        ),
    ]
