# Generated by Django 3.2.8 on 2021-10-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20211015_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsubmission',
            name='source',
            field=models.SmallIntegerField(choices=[(0, 'BASE_CODE'), (1, 'TEST_CODE')], default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'CREATED'), (1, 'CLONING'), (2, 'CLONED'), (3, 'UPLOADING'), (4, 'UPLOADED'), (5, 'VALIDATING'), (6, 'VALID'), (7, 'TESTING'), (8, 'PROCESSED'), (9, 'INVALID'), (10, 'ERROR'), (11, 'TIMEOUT')], default=0),
        ),
    ]
