# Generated by Django 3.2.8 on 2021-10-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20211015_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'CREATING'), (1, 'CREATED'), (2, 'CLONING'), (3, 'CLONED'), (4, 'UPLOADING'), (5, 'UPLOADED'), (6, 'MERGING'), (7, 'MERGED'), (8, 'TESTING'), (9, 'PROCESSED'), (10, 'INVALID'), (11, 'ERROR'), (12, 'TIMEOUT')], default=0),
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'ADDED'), (1, 'SKIPPED'), (2, 'FILTERED'), (3, 'GENERATED')], default=0),
        ),
    ]
