# Generated by Django 3.2.8 on 2021-10-16 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20211016_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='execution_path',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='execution',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'CREATING'), (1, 'CREATED'), (2, 'STARTING'), (3, 'RUNNING'), (4, 'FINISHED'), (5, 'INVALID'), (6, 'ERROR'), (7, 'TIMEOUT')], default=0),
        ),
        migrations.AlterField(
            model_name='execution',
            name='container_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='execution',
            name='started_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='execution',
            name='submission',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.submission'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'CREATING'), (1, 'CREATED'), (2, 'CLONING'), (3, 'CLONED'), (4, 'MERGING'), (5, 'MERGED'), (6, 'WAITING'), (7, 'TESTING'), (8, 'PROCESSED'), (9, 'INVALID'), (10, 'ERROR'), (11, 'TIMEOUT')], default=0),
        ),
    ]
