# Generated by Django 3.2.8 on 2021-10-17 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20211017_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('type', models.SmallIntegerField(choices=[(0, 'LEARNERS'), (1, 'SUBMISSIONS')], default=0)),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.coursegroup')),
            ],
        ),
        migrations.CreateModel(
            name='ImportSessionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, default=None, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('local_path', models.CharField(blank=True, max_length=255, null=True)),
                ('learner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.learner')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.importsession')),
            ],
        ),
    ]
