# Generated by Django 3.2.8 on 2021-10-17 16:28

from django.db import migrations, models
import pelp.apps.web.models.import_session


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_importsession_importsessionentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='input_file',
            field=models.FileField(blank=True, default=None, max_length=250, null=True, upload_to=pelp.apps.web.models.import_session.get_input_file_upload_path),
        ),
        migrations.AddField(
            model_name='importsession',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'CREATED'), (1, 'LOADING'), (2, 'LOADED'), (3, 'IMPORTING'), (4, 'IMPORTED')], default=0),
        ),
    ]
