# Generated by Django 3.2.8 on 2021-10-17 16:46

from django.db import migrations, models
import pelp.apps.web.models.import_session


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_importsession_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importsessionentry',
            name='local_path',
        ),
        migrations.AddField(
            model_name='importsessionentry',
            name='entry_file',
            field=models.FileField(blank=True, default=None, max_length=250, null=True, upload_to=pelp.apps.web.models.import_session.get_entry_file_upload_path),
        ),
    ]
