# Generated by Django 3.2.8 on 2021-10-18 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20211017_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('internal_code', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='web.projecttest')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.project')),
            ],
            options={
                'unique_together': {('project', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SubmissionTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=False)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.submission')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.projecttest')),
            ],
            options={
                'unique_together': {('submission', 'test')},
            },
        ),
    ]
