# Generated by Django 3.2.8 on 2021-10-19 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20211018_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.activity'),
        ),
    ]
