# Generated by Django 3.2.8 on 2021-10-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_importsession_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='error',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='error',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='error',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
