# Generated by Django 3.2.8 on 2021-10-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='error',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='importsessionentry',
            name='error',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_last',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='allowed_files_regex',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
