# Generated by Django 3.2.8 on 2021-10-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20211020_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'ANSI_C')], default=0),
        ),
    ]
