# Generated by Django 3.2.8 on 2021-10-20 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_project_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'NO_DATA'), (1, 'PENDING'), (2, 'VALID'), (3, 'INVALID'), (4, 'ERROR'), (5, 'TIMEOUT')], default=0)),
                ('num_submissions', models.IntegerField(default=0)),
                ('test_passed', models.BooleanField(default=False)),
                ('num_tests', models.IntegerField(default=0)),
                ('num_test_passed', models.IntegerField(default=0)),
                ('num_test_failed', models.IntegerField(default=0)),
                ('error', models.IntegerField(blank=True, default=None, null=True)),
                ('submitted_at', models.DateTimeField(default=None, null=True)),
                ('elapsed_time', models.IntegerField(default=None, null=True)),
                ('activity', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.activity')),
                ('last_submission', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.submission')),
                ('learner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.learner')),
            ],
            options={
                'unique_together': {('activity', 'learner')},
            },
        ),
    ]
