# Generated by Django 3.2.8 on 2021-10-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_alter_importsession_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerresult',
            name='error',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
