# Generated by Django 3.2.8 on 2021-10-26 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_instructormailsubmission_instructorsubmission_mailinbox_mailsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('locked_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
