# Generated by Django 3.2.8 on 2021-10-26 19:18

from django.db import migrations, models
import pelp.apps.web.models.mail_submission


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_tasklock'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsubmission',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=pelp.apps.web.models.mail_submission.get_attachment_upload_path),
        ),
    ]
