# Generated by Django 3.2.8 on 2021-10-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_mailsubmission_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsubmission',
            name='error',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
