# Generated by Django 3.2.8 on 2021-10-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_mailsubmission_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsubmission',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'CREATING'), (1, 'CREATED'), (2, 'IMPORTING'), (3, 'IMPORTED'), (4, 'INVALID'), (5, 'ERROR')], default=0),
        ),
    ]
