# Generated by Django 3.2.8 on 2021-10-26 21:07

from django.db import migrations, models
import pelp.apps.web.models.mail_inbox


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_mailsubmission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinbox',
            name='name',
            field=models.CharField(default=pelp.apps.web.models.mail_inbox.get_default_name, max_length=255, unique=True),
        ),
    ]
