# Generated by Django 3.2.8 on 2021-10-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_alter_mailinbox_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsubmission',
            name='from_mail',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='mailsubmission',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'CREATING'), (1, 'CREATED'), (2, 'IMPORTING'), (3, 'IMPORTED'), (4, 'INVALID'), (5, 'ERROR'), (6, 'OVERDUE')], default=0),
        ),
    ]
