# Generated by Django 3.2.8 on 2021-10-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_auto_20211027_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailsubmission',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'CREATING'), (1, 'CREATED'), (2, 'IMPORTING'), (3, 'IMPORTED'), (4, 'INVALID'), (5, 'ERROR'), (6, 'OVERDUE'), (7, 'OVER_QUOTA')], default=0),
        ),
    ]
