# Generated by Django 3.2.8 on 2021-10-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_auto_20211030_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissiontestresult',
            name='compiled',
        ),
    ]
