# Generated by Django 3.2.8 on 2021-10-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_remove_submissiontestresult_compiled'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='test_score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
