# Generated by Django 3.2.8 on 2021-10-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_submission_test_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerresult',
            name='test_score',
            field=models.FloatField(default=0.0),
        ),
    ]
