# Generated by Django 3.2.8 on 2021-11-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_auto_20211030_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='use_valgrind',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='valgrind_report_path',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
