# Generated by Django 3.2.8 on 2021-11-21 12:20

from django.db import migrations, models
import pelp.apps.web.models.submission


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_auto_20211121_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='valgrind_report',
            field=models.FileField(blank=True, null=True, upload_to=pelp.apps.web.models.submission.get_valgrind_upload_path),
        ),
    ]
