# Generated by Django 3.2.8 on 2021-11-24 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_submission_valgrind_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerresult',
            name='memory_leak',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='SubmissionError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'OTHER'), (1, 'MEMORY_OPERATION'), (2, 'MEMORY_LEAK'), (3, 'GENERATED')], default=0)),
                ('source', models.SmallIntegerField(choices=[(0, 'INSTRUCTOR'), (1, 'VALGRIND')], default=0)),
                ('order', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('count', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('code', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('context', models.TextField(blank=True, default=None, null=True)),
                ('value', models.FloatField(blank=True, default=None, null=True)),
                ('file', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.submissionfile')),
                ('submission', models.ForeignKey(blank=None, on_delete=django.db.models.deletion.CASCADE, to='web.submission')),
            ],
        ),
    ]
