# Generated by Django 3.2.8 on 2021-11-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_auto_20211124_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionerror',
            name='function',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='submissionerror',
            name='line',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
