# Generated by Django 3.2.8 on 2021-11-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_auto_20211125_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='leaked_bytes',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
