# Generated by Django 3.2.8 on 2021-12-20 08:25

from django.db import migrations, models
import pelp.apps.web.models.submission


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0043_submission_leaked_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='diff_report',
            field=models.FileField(blank=True, null=True, upload_to=pelp.apps.web.models.submission.get_diff_upload_path),
        ),
    ]
