# Generated by Django 3.2.8 on 2021-12-20 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_activityfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RubricElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, 'ADDITIVE'), (1, 'SUBTRACTIVE')], default=0)),
                ('description', models.TextField()),
                ('weight', models.FloatField(blank=True, default=None, null=True)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.rubric')),
            ],
        ),
        migrations.CreateModel(
            name='RubricElementOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('value', models.FloatField(default=1.0)),
                ('rubric_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.rubricelement')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='rubric',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.rubric'),
        ),
        migrations.CreateModel(
            name='RubricElementInstantiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.activity')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.learner')),
                ('rubric_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.rubricelement')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.rubricelementoption')),
            ],
            options={
                'unique_together': {('activity', 'learner', 'rubric_element')},
            },
        ),
    ]
