# Generated by Django 3.2.8 on 2022-01-06 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='web.rubric'),
        ),
        migrations.CreateModel(
            name='TranslateCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ca', 'Catalan'), ('es', 'Spanish'), ('en', 'English')], max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.course')),
            ],
        ),
        migrations.CreateModel(
            name='TranslateActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ca', 'Catalan'), ('es', 'Spanish'), ('en', 'English')], max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.activity')),
            ],
        ),
    ]
