# Generated by Django 3.2.8 on 2022-01-07 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0049_auto_20220106_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslateRubricElementOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ca', 'Catalan'), ('es', 'Spanish'), ('en', 'English')], max_length=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('rubric_element_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.rubricelementoption')),
            ],
        ),
        migrations.CreateModel(
            name='TranslateRubricElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ca', 'Catalan'), ('es', 'Spanish'), ('en', 'English')], max_length=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('rubric_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.rubricelement')),
            ],
        ),
    ]
