# Generated by Django 3.2.8 on 2022-01-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0051_activityfeedback_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_submissions',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_submissions_day',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
