# Generated by Django 3.2.8 on 2022-01-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0052_auto_20220109_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='set_official',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='result_summary',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
