# Generated by Django 3.2.8 on 2022-01-17 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0053_auto_20220112_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricActivityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=255)),
                ('learners', models.IntegerField()),
                ('np', models.IntegerField(default=0)),
                ('total_submissions', models.IntegerField(default=0)),
                ('score_a', models.IntegerField(default=0)),
                ('score_b', models.IntegerField(default=0)),
                ('score_cp', models.IntegerField(default=0)),
                ('score_cm', models.IntegerField(default=0)),
                ('score_d', models.IntegerField(default=0)),
                ('metadata', models.TextField(blank=True, default=None, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.historicactivity')),
            ],
            options={
                'unique_together': {('semester', 'course', 'code')},
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='historic_code',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.historicactivity'),
        ),
        migrations.CreateModel(
            name='HistoricActivityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=255)),
                ('instructors', models.CharField(max_length=255)),
                ('locale', models.CharField(max_length=10)),
                ('learners', models.IntegerField()),
                ('np', models.IntegerField(default=0)),
                ('score_a', models.IntegerField(default=0)),
                ('score_b', models.IntegerField(default=0)),
                ('score_cp', models.IntegerField(default=0)),
                ('score_cm', models.IntegerField(default=0)),
                ('score_d', models.IntegerField(default=0)),
                ('metadata', models.TextField(blank=True, default=None, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.historicactivitydata')),
            ],
            options={
                'unique_together': {('activity', 'group')},
            },
        ),
    ]
