# Generated by Django 3.2.8 on 2022-01-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0055_activity_self_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicactivitydata',
            name='observations',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicactivitygroup',
            name='observations',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
