# Generated by Django 3.2.8 on 2022-01-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0056_auto_20220117_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicactivitydata',
            old_name='np',
            new_name='score_np',
        ),
        migrations.RenameField(
            model_name='historicactivitygroup',
            old_name='np',
            new_name='score_np',
        ),
        migrations.AddField(
            model_name='historicactivitydata',
            name='eval_a',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicactivitydata',
            name='eval_b',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicactivitydata',
            name='eval_cm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicactivitydata',
            name='eval_cp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicactivitydata',
            name='eval_d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicactivitydata',
            name='eval_np',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicactivitydata',
            name='has_evaluation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicactivitydata',
            name='learners_with_submissions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicactivitydata',
            name='mean_submissions_learner',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicactivitygroup',
            name='eval_a',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicactivitygroup',
            name='eval_b',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicactivitygroup',
            name='eval_cm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicactivitygroup',
            name='eval_cp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicactivitygroup',
            name='eval_d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicactivitygroup',
            name='eval_np',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicactivitygroup',
            name='has_evaluation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicactivitygroup',
            name='learners_with_submissions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicactivitygroup',
            name='mean_submissions_learner',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicactivitygroup',
            name='total_submissions',
            field=models.IntegerField(default=0),
        ),
    ]
