# Generated by Django 3.2.8 on 2022-01-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0057_auto_20220117_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityfeedback',
            name='is_np',
            field=models.BooleanField(default=False),
        ),
    ]
