# Generated by Django 3.2.8 on 2022-01-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0064_auto_20220121_1227'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='translateactivity',
            unique_together={('activity', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='translatefaq',
            unique_together={('faq', 'language')},
        ),
        migrations.DeleteModel(
            name='TranslateFaqTag',
        ),
    ]
