# Generated by Django 3.2.8 on 2022-01-21 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0065_auto_20220121_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslateFaqTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ca', 'Catalan'), ('es', 'Spanish'), ('en', 'English')], max_length=5)),
                ('tag', models.CharField(max_length=255)),
                ('faqtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.faqtag')),
            ],
            options={
                'unique_together': {('faqtag', 'language')},
            },
        ),
    ]
