# Generated by Django 3.2.8 on 2022-02-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0066_translatefaqtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='allow_base_failure',
            field=models.BooleanField(default=False),
        ),
    ]
