# Generated by Django 3.2.8 on 2022-02-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0067_auto_20220223_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='include_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='report_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='submissionfile',
            name='is_report',
            field=models.BooleanField(default=False),
        ),
    ]
