# Generated by Django 3.2.8 on 2022-03-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0069_statisticsactivity_statisticsgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='is_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statisticsactivity',
            name='eval_pending',
            field=models.IntegerField(default=0),
        ),
    ]
