# Generated by Django 3.2.8 on 2022-03-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0071_statisticsgroup_eval_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticsactivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='statisticsgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
