# Generated by Django 3.2.8 on 2022-03-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0072_auto_20220304_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
