# Generated by Django 3.2.12 on 2022-10-19 18:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0073_activity_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.faq')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.learner')),
            ],
            options={
                'unique_together': {('faq', 'learner')},
            },
        ),
    ]
